import Head from 'next/head'
import Image from 'next/image'
import {Inter} from '@next/font/google'
import styles from '@/styles/Home.module.css'
import useBinaryFile from '../services/usebinaryFile'
import {useDB, useDBQuery} from '../services/useDB'
import {useState} from 'react'
import Link from 'next/link'

const inter = Inter({subsets: ['latin']})

export default function Home() {

  const data = useBinaryFile("/chinook.db")
  const db = useDB(data);

  const [query, setQuery] = useState("SELECT name FROM  sqlite_schema WHERE type ='table' AND name NOT LIKE 'sqlite_%';")
  const results = useDBQuery(db, query)

  const tables = results?.[0]?.values?.map((v) => v[0])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script type="module" src="/sql-loader.js" />

      </Head>
      <main className={styles.main}>
        <div className='w-full'>
          <h3 className='text-sm font-bold text-right'>download database file form <Link className="text-blue-500" href="/chinook.db">here</Link></h3>
        </div>
        <div className="text-center flext">
          <h1 className="text-3xl font-bold underline">
            {tables?.length} Tables
          </h1>
          <ul>
            {tables?.map((t) => <li key={t}>{t}</li>)}
          </ul>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

      </main>
    </>
  )
}
